name: Workflow testing

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Repo Branch/Tag'
        default: 'main'
        type: 'string'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.tag }}

      - name: 'get sha'
        run: |
          git rev-parse --short ${{ inputs.tag }}
          MYSHA=$(git rev-parse ${{ inputs.tag }})

      - name: env
        run: env
      

