---
name: 'Create Release'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.devcontainer/**'
      - '.**'
      - '**.md'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.manifest_release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_PLEASE_UAT }}
          command: manifest
          package-name: webssh2
          path: app
  publish:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      fail-fast: false
      matrix:
        path: ${{fromJson(needs.release.outputs.paths_released)}}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16
            registry-url: 'https://registry.npmjs.org'
        - name: Build Packages
          run: |
            cd ${{ matrix.path }}
            npm install
            npx lerna bootstrap
        # Release Please has already incremented versions and published tags, so we just
        # need to publish all unpublished versions to NPM here
        # See: https://github.com/lerna/lerna/tree/main/commands/publish#bump-from-package
        - name: Publish to NPM
          if: ${{ steps.release.outputs.releases_created }}
          working-directory: ./app
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          run: |
            cd ${{ matrix.path }}
            npx lerna publish from-package --no-push --no-private --yes